### ISSUE TITLE
Recursive type operator

### ISSUE THREAD

**Issue by robrix** [antitypical/Manifold#49]
µ X . …

**Comment by rgm** [comment]
In the spirit of TAPL so far, you should assume it as an operator implemented somewhere deep in LLVM, and just close the issue.

**Comment by robrix** [comment]
That’ll have to wait for me to implement a compiler. In the meantime, type operator it is.

**Comment by robrix** [comment]
Actually I don’t think this is what I want at all. I want inductive data types and coinductive codata types but not general recursion at the type level (since once we have #45 in place that’ll mean general recursion at the term level which will make typechecking undecidable in general).
